<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Facility selection box</name>
   <tag></tag>
   <elementGuidId>0091b054-dce6-4d26-85aa-c25c688319c4</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>xpath1732174396369</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name = 'facility']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>4e007c88-ad77-4d1e-94bf-917778bc37d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1732174396369</value>
      <webElementGuid>f1f37896-9153-4667-86ff-d798fdf391e4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
